version: "3"
services:
  api:
    build: ./api
    depends_on:
      - db
    env_file:
      - ./api/.env
    ports:
      - 3001:3000
    # Uncomment for development purposes
    # volumes:
    #   - ./api:/app

  front:
    build: ./front
    env_file:
      - ./front/.env
    ports:
      - 3000:3000
    # Uncomment for development purposes
    # volumes:
    #   - ./front/:/app

  db:
    build: ./db
    env_file:
      - ./db/.env
    # Uncomment for dev purposes and using dockerized postgresql
    # ports:
    #   - 5432:5432
    # volumes:
    #  - "./db/data/:/var/lib/postgresql/data"

  adminer:
    depends_on:
      - db
    image: adminer
    ports:
      - 3002:8080
