version: '3'
services:

  api:
    build: ./api
    command: bash -c "rm -f tmp/pids/server.pid && rake db:migrate && bundle exec rails s -p 3001 -b '0.0.0.0'"
    volumes:
      - ./api:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - api.env

  front:
    build: ./front
    ports:
      - 3000:3000
    volumes:
      - ./front/:/app

  db:
    build: ./db
    volumes:
      - "./db/data/:/var/lib/postgresql/data"
    ports:
      - 5432:5432
    env_file:
      - db.env

  adminer:
    image: adminer
    ports:
      - 8080:3002
    depends_on:
      - db
