default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: rails
  password: rails
  host: db

development:
  <<: *default
  database: theater_dev

production:
  <<: *default
  database: theater_prod

test:
  <<: *default
  database: theater_test