default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: test
  password:

development:
  <<: *default
  database: theater_dev

production:
  <<: *default
  database: theater_prod

test:
  <<: *default
  database: theater_test