require:
  - rubocop-rspec

AllCops:
  Exclude:
    - bin/**/*
    - db/schema.rb
  DisplayCopNames: true

Style/Documentation:
  Exclude:
    - app/controllers/*

Style/FrozenStringLiteralComment:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/RescueStandardError:
  EnforcedStyle: implicit

Metrics/AbcSize:
  Max: 15

Metrics/BlockLength:
  ExcludedMethods: ['let', 'context', 'define', 'describe', 'factory', 'shared_examples', 'shared_context']

Metrics/BlockNesting:
  Max: 3

Metrics/ClassLength:
  CountComments: false
  Max: 200

# Avoid complex methods
Metrics/CyclomaticComplexity:
  Max: 6

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  CountComments: false
  Max: 25

Metrics/ModuleLength:
  CountComments: false
  Max: 200

Metrics/PerceivedComplexity:
  Max: 7

RSpec/AnyInstance:
  Enabled: false

RSpec/ImplicitSubject:
  Enabled: false